version: '3.8'
services:
  dev:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: gchoudhary
      POSTGRES_PASSWORD: jewXab-dacwu7-wiwdad
      POSTGRES_DB: bharatapplydb
    networks:
      - bharatapply
    volumes:
      - /var/lib/postgres

  nest-cloud-run:
    image: nest-cloud-run
    environment:
      POSTGRES_USER: gchoudhary
      POSTGRES_PASSWORD: jewXab-dacwu7-wiwdad
      POSTGRES_DB: bharatapplydb
    ports:
      - '3000:3000'
    depends_on:
      - dev
    networks:
      - bharatapply

  test:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: gchoudhary
      POSTGRES_PASSWORD: jewXab-dacwu7-wiwdad
      POSTGRES_DB: bharatapplydb
    networks:
      - bharatapply

networks:
  bharatapply:
    driver: bridge
