-- AlterTable
ALTER TABLE "grades" ADD COLUMN     "classTenBoard" TEXT,
ADD COLUMN     "classTenEnrollmentNo" INTEGER,
ADD COLUMN     "classTenExaminationCity" TEXT,
ADD COLUMN     "classTenExaminationState" TEXT,
ADD COLUMN     "classTenGradeType" TEXT,
ADD COLUMN     "classTenInfoAccurate" BOOLEAN DEFAULT false,
ADD COLUMN     "classTenMarks" DOUBLE PRECISION,
ADD COLUMN     "classTenPassingMonth" TEXT,
ADD COLUMN     "classTenPassingYear" INTEGER,
ADD COLUMN     "classTenPercentage" DOUBLE PRECISION,
ADD COLUMN     "classTenSchoolName" TEXT,
ADD COLUMN     "classTenTotalMarks" DOUBLE PRECISION,
ADD COLUMN     "classTwelveBoard" TEXT,
ADD COLUMN     "classTwelveEnrollmentNo" INTEGER,
ADD COLUMN     "classTwelveExaminationCity" TEXT,
ADD COLUMN     "classTwelveExaminationState" TEXT,
ADD COLUMN     "classTwelveGradeType" TEXT,
ADD COLUMN     "classTwelveInfoAccurate" BOOLEAN DEFAULT false,
ADD COLUMN     "classTwelveMarks" DOUBLE PRECISION,
ADD COLUMN     "classTwelvePassingMonth" TEXT,
ADD COLUMN     "classTwelvePassingYear" TEXT,
ADD COLUMN     "classTwelvePercentage" DOUBLE PRECISION,
ADD COLUMN     "classTwelveSchoolName" TEXT,
ADD COLUMN     "classTwelveSpecialization" TEXT,
ADD COLUMN     "classTwelveStatus" TEXT,
ADD COLUMN     "classTwelveStream" TEXT,
ADD COLUMN     "classTwelveTotalMarks" DOUBLE PRECISION,
ADD COLUMN     "classTwelveType" TEXT;
